name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ghcr.io/railwayapp/cli:3.15.3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Deploy to Railway
      run: |
        railway init --name "$RAILWAY_PROJECT_NAME"
        railway up --detach
