name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_NAME }}
      run: |
        curl -sL https://raw.githubusercontent.com/railwayapp/cli/refs/heads/master/install.sh | sh
        railway init --name "$RAILWAY_PROJECT_NAME"
        RAILWAY_TOKEN=$RAILWAY_TOKEN railway up --detach
